/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 57380daeda5562cf7008c0480cbc61f4)
interface __BaseEnv_Env {
	SESSION_MEMORY: KVNamespace;
	TELEGRAM_JOBS: Queue;
	LINE_API_BASE_URL: string;
	TELEGRAM_API_BASE_URL: string;
	WHATSAPP_API_BASE_URL: string;
	WHATSAPP_ACCESS_TOKEN: string;
	WHATSAPP_PHONE_NUMBER_ID: string;
	WHATSAPP_VERIFY_TOKEN: string;
	WHATSAPP_APP_SECRET: string;
	OPENAI_BASE_URL: string;
	OPENAI_MODEL: string;
	OPENAI_MAX_TOOL_ROUNDS: string;
	OPENAI_MAX_TOOL_CALLS: string;
	GITHUB_API_BASE_URL: string;
	GITHUB_REF: string;
	SESSION_MEMORY_MAX_MESSAGES: string;
	LINE_CHANNEL_SECRET: string;
	LINE_CHANNEL_ACCESS_TOKEN: string;
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_WEBHOOK_SECRET: string;
	TELEGRAM_ALLOWED_USER_IDS: string;
	OPENAI_API_KEY: string;
	GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LINE_API_BASE_URL" | "TELEGRAM_API_BASE_URL" | "WHATSAPP_API_BASE_URL" | "WHATSAPP_ACCESS_TOKEN" | "WHATSAPP_PHONE_NUMBER_ID" | "WHATSAPP_VERIFY_TOKEN" | "WHATSAPP_APP_SECRET" | "OPENAI_BASE_URL" | "OPENAI_MODEL" | "OPENAI_MAX_TOOL_ROUNDS" | "OPENAI_MAX_TOOL_CALLS" | "GITHUB_API_BASE_URL" | "GITHUB_REF" | "SESSION_MEMORY_MAX_MESSAGES" | "LINE_CHANNEL_SECRET" | "LINE_CHANNEL_ACCESS_TOKEN" | "TELEGRAM_BOT_TOKEN" | "TELEGRAM_WEBHOOK_SECRET" | "TELEGRAM_ALLOWED_USER_IDS" | "OPENAI_API_KEY" | "GITHUB_TOKEN">> {}
}
declare module "*.md" {
	const value: string;
	export default value;
}